// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnN1Mx130hcftNL5e7t63cQRaxwpKB4-Q',
    appId: '1:282402832864:web:dc3c790fd67a9b32aa6b85',
    messagingSenderId: '282402832864',
    projectId: 'treepy-4cc05',
    authDomain: 'treepy-4cc05.firebaseapp.com',
    storageBucket: 'treepy-4cc05.appspot.com',
    measurementId: 'G-Y2NELGCX4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL2xh2WCart4zh1zzPHPRO_LJ0oPHGkSM',
    appId: '1:282402832864:android:7774e454633aca50aa6b85',
    messagingSenderId: '282402832864',
    projectId: 'treepy-4cc05',
    storageBucket: 'treepy-4cc05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDspxzu4KdThM5d5OjPUSEKuI57x16fXHc',
    appId: '1:282402832864:ios:a3c5aabadcbfdcf7aa6b85',
    messagingSenderId: '282402832864',
    projectId: 'treepy-4cc05',
    storageBucket: 'treepy-4cc05.appspot.com',
    iosClientId: '282402832864-6qei8a4k0umvbfq7nhs6d2rcsffv73dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.treepy',
  );
}
